1

In [1]:
import numpy as np

2

In [4]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

3

In [6]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4

In [18]:
z.size * z.itemsize

80

5

In [19]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [20]:
# 6
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
# 7
vec = np.arange(10, 50)
print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [27]:
# 8
z = np.arange(9)
z = z.reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
# 9
print(np.nonzero([1,2,0,0,4,0]))


(array([0, 1, 4], dtype=int64),)


In [54]:
# 10
z = np.identity(3)
z
# Alternative
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
# 11
z = np.random.random((3,3,3))
z

array([[[0.17793233, 0.90249475, 0.6851607 ],
        [0.37337637, 0.00378806, 0.87779278],
        [0.18025121, 0.46017903, 0.52960814]],

       [[0.73616816, 0.61167041, 0.05132676],
        [0.99856971, 0.43203195, 0.18053531],
        [0.6064066 , 0.92680273, 0.12393823]],

       [[0.65007157, 0.32716087, 0.87749611],
        [0.72492292, 0.94586181, 0.60542856],
        [0.798991  , 0.79328624, 0.56630995]]])

In [63]:
# 12
z = np.random.random((10,10))
print(z.min())
print(z.max())

0.01826953189069369
0.9945879519672544


In [70]:
# 14
new = np.random.randint(100, size=30)
z = new.mean()
z

51.2

In [76]:
# 15
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
# 16
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [103]:
# 17
print(0.3 == 0.3)

True


In [10]:
# 18
z = np.diag(np.arange(1,5), k= -1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [15]:
# 19
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
z = np.zeros(8, dtype=int)
z[::2] = 1
a = np.tile(z, (8)).reshape((8,8))
a[1::2, ::2] = 0
a[1::2, 1::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [26]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


## Numpy Raw Just Learning

In [16]:
a = np.arange(1, 13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a = np.arange(1, 13).reshape((3,4))
b = a[[0,2], [0-3]]
print(b.base)

None


In [63]:
a = np.array([1, 2, 3, 4, 5, 6, 7 , 8])
b = a[1:]
b[0] = 5

print(b.base)

[1 5 3 4 5 6 7 8]


In [68]:
nums = np.genfromtxt(r'C:\Users\user\Desktop\PythonMaab\numers.txt', delimiter=',')
nums

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
nums = nums.astype(np.int32)
nums
nums.sum()

21

In [77]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
b = np.array([[7, 8, 9],
             [10, 11, 12]])
np.append(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])